### PR TITLE
Twemoji 14.0.2

### PR DESCRIPTION
**Pull request by win98se**
Based on https://github.com/mozilla/twemoji-colr/pull/65

### CODE REVIEW

**Comment by Feodor2** [comment]
You are to elaborate carefully what is this about, why do yo want me pull this stuff. 
While i have many things to do i do not know when i shall examine it myself.

**Comment by win98se** [comment]
It is Emoji 14.0 (which is the latest version of Unicode emoji standard as of today) support.

Since the upstream project (which is Firefox) uses Twemoji as the alternative emoji font, it seems to be better to follow up with latest emoji standards instead of stucking with Firefox 68's.

Not top priority though, you can review it as you suit.

**Comment by Feodor2** [comment]
> better to follow up with latest emoji standards

Why? This is a font of symbolos winxp does not recognize, both old and new. Also new is 0.27 mb bigeer

**Comment by win98se** [comment]
> Why? This is a font of symbolos winxp does not recognize, both old and new.

Not exactly; Such fonts are not meant to be installed in Windows, however Firefox-based browsers' renderers do render the emojis correctly, even under Windows XP. Proof -

image
(Left is Mypal 29.3.0, right is Mypal68, both under Windows XP)

This is the result of using the older font included in the release -

image

> Also new is 0.27 mb bigeer

0.27 MB increase in size is quite “not that big” in this case as well - comparing two versions of the font, there are about 832 more supported emojis (which are additions from Emoji 12-14).

I do not intend to persuade you any further on this. After all, the choices are on you.

**Comment by K4sum1** [comment]
Why close?

**Comment by 1280px** [comment]
+1, closing this pr makes no sense. Everyone will benefit from better modern Emoji support, and the PR itself seems to contain no problems.

**Pull request closed without merging**
