### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 777Shinichi777**

### CODE REVIEW

**Review by win98se — COMMENTED** [review]
Meaningless commit.
It is too big of an action (like opening a pull request) if you want to ask for Feodor2's e-mail address.

**Comment by 1280px** [comment]
That's not how pull requests work

**Comment by win98se** [comment]
@1280px Yup, there's no need for a thumbs down react though... I see he is quite a newbie in version controls I guess?

**Comment by Feodor2** [comment]
I looked here occasionally and i do not want my email anybody spammed.

**Pull request closed without merging**
